server:
  port: 8080 # ???????
spring:
  security:
    user:
      name: yhl
      password: "yhl"
  datasource:
    name: postgres2
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379


