server:
  port: 8080 # ???????
spring:
  security:
    user:
      name: yhl
      password: "yhl"
  datasource:
    name: postgres2
    url: jdbc:mysql://127.0.0.1:3306/mysystem
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379


